export const dummyFiles = [
  {
    $id: "1",
    name: "Sample PDF Document.pdf",
    type: "document",
    extension: "pdf",
    url: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
    $createdAt: new Date().toISOString(),
    owner: { fullName: "Demo User" },
  },
  {
    $id: "2",
    name: "Sample PDF 2.pdf",
    type: "document",
    extension: "pdf",
    url: "https://file-examples.com/wp-content/uploads/2017/10/file-sample_150kB.pdf",
    $createdAt: new Date().toISOString(),
    owner: { fullName: "Demo User" },
  },
  {
    $id: "3",
    name: "Unsplash Mountain.jpg",
    type: "image",
    extension: "jpg",
    url: "https://images.unsplash.com/photo-1506744038136-46273834b3fb",
    $createdAt: new Date().toISOString(),
    owner: { fullName: "Demo User" },
  },
  {
    $id: "4",
    name: "Unsplash Forest.jpg",
    type: "image",
    extension: "jpg",
    url: "https://images.unsplash.com/photo-1465101046530-73398c7f28ca",
    $createdAt: new Date().toISOString(),
    owner: { fullName: "Demo User" },
  },
  {
    $id: "5",
    name: "Sample Video.mp4",
    type: "video",
    extension: "mp4",
    url: "https://www.w3schools.com/html/mov_bbb.mp4",
    $createdAt: new Date().toISOString(),
    owner: { fullName: "Demo User" },
  },
  {
    $id: "6",
    name: "Big Buck Bunny.mp4",
    type: "video",
    extension: "mp4",
    url: "https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_1mb.mp4",
    $createdAt: new Date().toISOString(),
    owner: { fullName: "Demo User" },
  },
];
